### PR TITLE
Adds --role,--region,--url options for cfn-init and cfn-signal to work HS

### PR DESCRIPTION
**Pull request by dvu70**

### CODE REVIEW

**Comment by ferricoxide** [comment]
Ah, yeah: had forgotten to add those...

**Comment by dvu70** [comment]
Yeah, short flag some, long others. Made them all long. Re tested and it ran cleanly. I'll refresh hs with your commits today and do another run.

**Comment by dvu70** [comment]
Oh, i meant tested hs. Did you mean low?

**Comment by ferricoxide** [comment]
Need to test in both the production networks and lab: need to ensure that fixing for the production networks doesn't break for the dev networks. =)

I know: belt-and-suspenders - but ran into cases where fixes for prod in AMIgen broke it for dev. :\

**Comment by ferricoxide** [comment]
Running a stack-test, now (waiting for RDS...)

**Comment by ferricoxide** [comment]
Oop... Missed the timestamp on this. That was a waste of time to run the stack. :p

**Pull request merged**
